name: chat_craft
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #localiztion
  intl: ^0.18.1

  #state manger
  get: ^4.6.6

  #network
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8


  #localDb
  shared_preferences: ^2.2.2


  #ui utils
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.2
  just_audio: ^0.9.35
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  webview_flutter: ^4.4.1
  dots_indicator: ^3.0.0
  location: ^5.0.3

  #utils
  crypto: ^3.0.3
  share_plus: ^7.2.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  uni_links: ^0.5.1


  #google
  google_sign_in: ^6.1.5
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_in_app_messaging: ^0.7.3+7
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/icon/
    - assets/images/



