///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconBackspace = 'assets/icon/backspace.svg';
  static const String iconCheckBig = 'assets/icon/check_big.svg';
  static const String iconChevronDown = 'assets/icon/chevron_down.svg';
  static const String iconChevronLeft = 'assets/icon/chevron_left.svg';
  static const String iconChevronRight = 'assets/icon/chevron_right.svg';
  static const String iconChevronUp = 'assets/icon/chevron_up.svg';
  static const String iconCloseSmall = 'assets/icon/close_small.svg';
  static const String iconFile = 'assets/icon/file.svg';
  static const String iconFolder = 'assets/icon/folder.svg';
  static const String iconGroup = 'assets/icon/group.svg';
  static const String iconHamburger = 'assets/icon/hamburger.svg';
  static const String iconHelpCircle = 'assets/icon/help_circle.svg';
  static const String iconHide = 'assets/icon/hide.svg';
  static const String iconKeyboardShiftUppercase =
      'assets/icon/keyboard_shift_uppercase.svg';
  static const String iconListCheck = 'assets/icon/list_check.svg';
  static const String iconListPlus = 'assets/icon/list_plus.svg';
  static const String iconMail = 'assets/icon/mail.svg';
  static const String iconMessageCircle = 'assets/icon/message_circle.svg';
  static const String iconMessagePlusAlt = 'assets/icon/message_plus_alt.svg';
  static const String iconMoreHorizontal = 'assets/icon/more_horizontal.svg';
  static const String iconNotification = 'assets/icon/notification.svg';
  static const String iconOutlineKeyboardVoice =
      'assets/icon/outline_keyboard_voice.svg';
  static const String iconOutlinePrivacyTip =
      'assets/icon/outline_privacy_tip.svg';
  static const String iconPlay = 'assets/icon/play.svg';
  static const String iconPlus = 'assets/icon/plus.svg';
  static const String iconPlusCircle = 'assets/icon/plus_circle.svg';
  static const String iconPlusCircleOutline =
      'assets/icon/plus_circle_outline.svg';
  static const String iconSearch = 'assets/icon/search.svg';
  static const String iconSendAltFilled = 'assets/icon/send_alt_filled.svg';
  static const String iconSun = 'assets/icon/sun.svg';
  static const String iconUser = 'assets/icon/user.svg';
  static const String imagesUserTalk = 'assets/images/user_talk.svg';
  static const String musicDang = 'assets/music/dang.mp3';
  static const String musicDing = 'assets/music/ding.mp3';
}
